inherit_from: .rubocop_todo.yml

# 追加した規約ファイルを読み込み
require:
  - rubocop-rails


AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    # - 'db/migrate/*'
    - 'Gemfile'


# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# 「frozen_string_literal: true」を追加しない
Style/FrozenStringLiteralComment:
  Enabled: false

# メソッドの行数が 10 行までは厳しすぎるので，20行までに変更
Metrics/MethodLength:
  Max: 20

# private/protected は一段深くインデントする
Style/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
